spring:
    application:
        name: user
    profiles:
        active: 'dev'
    data:
        mongodb:
            database: scnsoft
            port: 27017
            host: localhost

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

---
spring:
    profiles: dev
server:
    port: 8085
---
spring:
    profiles: prod
server:
    prod: 8084