version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
     - 8765:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq_container
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
      
  eureka:
    image: gredel/casino-eureka:latest
    ports:
      - 8761:8761
    restart: always
    
  gateway:
    image: gredel/casino-gateway:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - eureka

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  data: {}
