server:
  port: 8080

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
            fetch-registry: true
            register-with-eureka: true
        # fetch-registry: false
        # register-with-eureka: false
        # enabled: true

spring:
    application:
      name: gateway-service
    cloud:
        gateway:
            routes:
              - id: user-service
                uri: lb://USER-SERVICE/
                predicates:
                  - Path=/user-service/**
                filters:
                  - RewritePath=/user-service/(?<segment>.*),/$\{segment}


logging:
    level:
        reactor:
            netty: INFO
        org:
            springframework:
                cloud:
                    gateway: INFO
