app:
    winrate: 0.50

spring:
    application:
        name: bet
    profiles: 
        active: 'dev'

eureka:
    client:
        service-url: 
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

---

spring:
    profiles: dev
server:
    port: 8081

invoice:
    url: http://localhost:8083

user:
    url: http://localhost:8085

---

spring:
    profiles: prod
server:
    prod: 8080