spring:
    application:
        name: invoice
    profiles:
        active: 'dev'

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

---

spring:
    profiles: dev
server:
    port: 8083

---

spring:
    porfiles: prod
server:
    port: 8082