spring:
    application:
        name: invoice-service
    data:
        mongodb:
            database: invoice_db
            port: 27017
            host: localhost
    profiles:
        active: 'dev'

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

---

spring:
    profiles: dev
server:
    port: 8083

---

spring:
    porfiles: prod
server:
    port: 8082